name: Bug Report
description: Create a report to help us improve.
title: "[BUG]: "
labels:
  - "bug"
body:
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: Please describe what happened.
      placeholder: My component goes out of screen bounds when I pinch.

  - type: textarea
    id: actual-behaviour
    validations:
      required: true
    attributes:
      label: Actual Behavior
      placeholder: My component goes out of screen bounds.

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected Behavior
      placeholder: My component should not go out of the screen bounds.

  - type: textarea
    id: versions
    validations:
      required: true
    attributes:
      label: Versions
      description: What versions of Reanimated, Gesture Handler and this library are you using?
      placeholder: |
        1. React Native version
        2. Reanimated version
        3. Gesture Handler version
        4. react-native-zoom-toolkit version

  - type: textarea
    id: steps-to-reproduce
    validations:
      required: false
    attributes:
      label: Steps to Reproduce
      description: >-
        If you can reproduce this bug consistently, please describe the steps,
        a reproducible demo or an Expo Snack are welcome additions.
      placeholder: |
        1. Go to file X
        2. Add X property to component Y

  - type: textarea
    id: additional-context
    validations:
      required: false
    attributes:
      label: Additional Context
      description: Anything else you consider relevant to this issue.
      placeholder: Platform, Development environment, Package.json, etc.
