name: Bug Report
description: Create a report to help us improve.
title: "[Bug]: "
labels:
  - "bug"
body:
  - type: textarea
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: Please describe your issue in detail, attach footage if appropriate.

  - type: textarea
    id: additional-context
    validations:
      required: true
    attributes:
      label: Environment
      description: Provide relevant information about your environment.
      placeholder: Platform, Package.json or anything you consider relevant to your issue.

  - type: textarea
    id: steps-to-reproduce
    validations:
      required: false
    attributes:
      label: Steps to Reproduce
      description: >-
        If you can reproduce this bug consistently, please describe the steps.
        A reproducible demo or an Expo Snack are welcome additions.
      placeholder: |
        1. Go to file X
        2. Add X property to component
