name: Feature Request
description: Didn't you find what you need? Let us know.
title: "[FEATURE]: "
labels:
  - "enhancement"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: Please describe the need and/or possible use cases for this feature.

  - type: textarea
    validations:
      required: false
    attributes:
      label: Expected API
      description: Please describe how the API for this feture should look like.
