name: Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels:
  - "enhancement"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: Please describe the need and/or possible use cases for this feature.

  - type: textarea
    validations:
      required: false
    attributes:
      label: Expected API
      description: Please describe how the API for this feature should look like.
