name: Ask a question
description: Make sure you've read the documentation carefully before asking a question.
title: "[Question]: "
labels:
  - "question"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: You can ask many questions at once, however, make sure such questions are related to your issue's title.
      placeholder: Can i use this library for some random task?
