name: Ask a question
description: Make sure you've read the documentation carefully before asking a question.
labels:
  - "question"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: What Would You Like to Know?
      description: All questions are valid questions!
      placeholder: Does this library works with this other library?
